# This is a basic workflow to help you get started with Actions

name: Build new CV version

on:
  workflow_dispatch:

jobs:
  build-cv:
    if: (github.event.pusher.name == github.event.repository.owner.name)
    name: Build CV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove previous version
        run: |
          rm -rf cv.pdf
          
      - name: Latex to PDF
        uses: xu-cheng/latex-action@v2
        with:
         root_file: |
           cv.tex
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: PDF
         path: cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: New Version
        run: |
          git config user.email "me@juanvaldivia.dev"
          git config user.name "jsmvaldivia"
          git add cv.pdf
          git commit -a -m "New CV version"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
         
