# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world! Starting something

      - name: Latex to PDF
        uses: xu-cheng/latex-action@v2
        with:
         root_file: |
           cv.tex
