# This is a basic workflow to help you get started with Actions

name: Build new CV version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-cv:
    if: (github.event.pusher.name == github.event.repository.owner.name)
    name: Build CV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Latex to PDF
        uses: xu-cheng/latex-action@v2
        with:
         root_file: |
           cv.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
         name: PDF
         path: cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
         
